"""Add favorite_biomarkers column to profiles

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2025-04-02 21:11:00.000000 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = None # Set this if there was a previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added command to add the column
    op.add_column('profiles', sa.Column('favorite_biomarkers', sa.JSON(), nullable=True, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added command to drop the column
    op.drop_column('profiles', 'favorite_biomarkers')
    # ### end Alembic commands ###
